name: Update HTML File

on:
  schedule:
    - cron: '*/10 * * * *'  # Atualiza a cada 10 minutos

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python script to update HTML
        run: |
          python3 update_html.py
        
      - name: Commit updated file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add 0_est_mey.html
          git commit -m "Update HTML file"
          git push
