name: Update HTML

on:
  push:
    branches:
      - main  # ou a branch principal do seu repositório

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # ou a versão do Python que você usa

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 deep_translator

      - name: Run script to update HTML
        run: python atualizar_html.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add 0_est_mey.html
          git commit -m 'Atualizar HTML'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
